// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaSvzIl5ReevtmBBWTM4VbmdV6BVuJNik',
    appId: '1:754294207016:web:1220fb23703b0ecf90bb1d',
    messagingSenderId: '754294207016',
    projectId: 'magus-4a0d9',
    authDomain: 'magus-4a0d9.firebaseapp.com',
    storageBucket: 'magus-4a0d9.firebasestorage.app',
    measurementId: 'G-P9MZ2ZG0R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI8FPkU7VivsDXo3EVE8v0LkL-rse1lsU',
    appId: '1:754294207016:android:b34da9901e40a26990bb1d',
    messagingSenderId: '754294207016',
    projectId: 'magus-4a0d9',
    storageBucket: 'magus-4a0d9.firebasestorage.app',
  );
}
